title: Walter Reilly
logo: "/assets/img/walter_reilly.png?raw=true"
description: 
  Learning Scientist
  <br><br>

  <a href="/assets/img/walterreiily_resume_10_22.pdf">Resume</a> <a href="https://www.linkedin.com/in/wbreilly/">LinkedIn</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
