title: Walter Reilly
logo: "/assets/img/walter_reilly.png?raw=true"
description: 
  Learning Scientist
  <br><br>

  <a href="https://www.linkedin.com/in/wbreilly/">My LinkedIn Profile</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
